"""empty message

Revision ID: c733104ad68a
Revises: 36d71fa5ba40
Create Date: 2020-05-13 22:22:20.869374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c733104ad68a'
down_revision = '36d71fa5ba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_type', sa.Column('title', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'class_type', ['title'])
    op.drop_column('class_type', 'class_type')
    op.create_unique_constraint(None, 'instructor', ['phone'])
    op.create_unique_constraint(None, 'instructor', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor', type_='unique')
    op.drop_constraint(None, 'instructor', type_='unique')
    op.add_column('class_type', sa.Column('class_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_type', type_='unique')
    op.drop_column('class_type', 'title')
    # ### end Alembic commands ###
