"""empty message

Revision ID: 36d71fa5ba40
Revises: 24d3cecaf4cd
Create Date: 2020-05-13 21:34:12.988199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d71fa5ba40'
down_revision = '24d3cecaf4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_class_type',
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('class_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_type.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], )
    )
    op.drop_constraint('class_type_instructor_id_fkey', 'class_type', type_='foreignkey')
    op.drop_column('class_type', 'instructor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_type', sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('class_type_instructor_id_fkey', 'class_type', 'instructor', ['instructor_id'], ['id'])
    op.drop_table('instructor_class_type')
    # ### end Alembic commands ###
