"""empty message

Revision ID: 8e9c70f2d9ff
Revises: fd587c0f6c00
Create Date: 2020-05-19 23:02:24.433567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9c70f2d9ff'
down_revision = 'fd587c0f6c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'instructor', ['name'])
    op.create_unique_constraint(None, 'venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'instructor', type_='unique')
    # ### end Alembic commands ###
