"""empty message

Revision ID: fd587c0f6c00
Revises: 6717b99664e8
Create Date: 2020-05-15 15:44:57.538400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd587c0f6c00'
down_revision = '6717b99664e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'capacity')
    # ### end Alembic commands ###
